# Standards: 0.1
---
- name: Download repo key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    id: 46095ACC8548582C1A2699A9D27D666CD88E42B4
    state: present
  tags:
    - auditbeat

- name: Add apt repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/6.x/apt stable main
    filename: elastic
    update_cache: yes
    state: present
  tags:
    - auditbeat

- name: Install required packages
  loop:
    - auditbeat
  package:
    name: '{{ item }}'
    state: present
  tags:
    - auditbeat

- name: Start auditbeat service
  systemd:
    name: auditbeat
    state: '{{ auditbeat_service_state }}'
    daemon_reload: yes
    masked: no
    enabled: '{{ auditbeat_service_enabled }}'
  tags:
    - auditbeat

...
