---
- name: Remove legacy key
  ansible.builtin.apt_key:
    id: 46095ACC8548582C1A2699A9D27D666CD88E42B4
    state: absent
  tags:
    - auditbeat

- name: Remove legacy repo
  ansible.builtin.apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{ auditbeat_major_version }}.x/apt stable main"
    filename: elastic
    update_cache: False
    state: absent
  tags:
    - auditbeat

- name: Download repo key
  ansible.builtin.shell:
    cmd: "curl -sSL 'https://artifacts.elastic.co/GPG-KEY-elasticsearch' | gpg --dearmor --output {{ auditbeat_keyring }}"
    creates: "{{ auditbeat_keyring }}"
  tags:
    - auditbeat

- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ auditbeat_keyring }}] https://artifacts.elastic.co/packages/{{ auditbeat_major_version }}.x/apt stable main"
    filename: elastic
    update_cache: True
    state: present
  tags:
    - auditbeat

- name: Install required packages
  loop:
    - auditbeat
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  tags:
    - auditbeat

- name: Detect suid/guid files
  when:
    - auditbeat_suid_guid_rule_enabled
    - auditbeat_suid_guid_rule_files | length == 0
  register: auditbeat_suid_guid_rule_exec
  changed_when: False
  ansible.builtin.command: find / -xdev \( -perm -4000 -o -perm -2000 \) -type f
  tags:
    - auditbeat

- name: Fact suid/guid files
  when:
    - auditbeat_suid_guid_rule_enabled
    - auditbeat_suid_guid_rule_files | length == 0
  ansible.builtin.set_fact:
    auditbeat_suid_guid_rule_files: "{{ auditbeat_suid_guid_rule_exec.stdout_lines }}"
  tags:
    - auditbeat

- name: Drop reference config
  ansible.builtin.file:
    path: /etc/auditbeat/auditbeat.reference.yml
    state: absent
  tags:
    - auditbeat

- name: Write rules config
  notify:
    - Restart auditbeat
  loop: "{{ auditbeat_default_rules + auditbeat_group_rules + auditbeat_host_rules }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.state | default('present') == 'present'
  ansible.builtin.template:
    src: rules.j2
    dest: "{{ auditbeat_rules_path }}/{{ item.weight | default('10') }}_{{ item.name }}.conf"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - auditbeat

- name: Drop rules config
  notify:
    - Restart auditbeat
  loop: "{{ auditbeat_default_rules + auditbeat_group_rules + auditbeat_host_rules }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.state | default('present') == 'absent'
  ansible.builtin.file:
    path: "{{ auditbeat_rules_path }}/{{ item.weight | default('10') }}_{{ item.name }}.conf"
    state: absent
  tags:
    - auditbeat

- name: Write general config
  notify:
    - Restart auditbeat
  ansible.builtin.template:
    src: config.j2
    dest: /etc/auditbeat/auditbeat.yml
    validate: "{{ auditbeat_test_config_command }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - auditbeat

- name: Start auditbeat service
  ansible.builtin.systemd:
    name: auditbeat
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - auditbeat

...
